spring:
  application:
    name: api-gateway
  cloud:
    gateway:
#      routes:
#        - id: product-microservice
#          uri: lb://product-microservice
#          predicates:
#            - Path=/product-microservice/*
#          filters:
#            - StripPrefix=1
#
#        - id: orders-service
#          uri: lb://orders-service
#          predicates:
#            - Path=/orders-service/*
#          filters:
#            - StripPrefix=1

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

#logging:
#  level:
#    root: debug
